Most of this tutorial is cobbled together from parts of "How to think like a computer scientist: Learning with Python." This is a great resource that goes a lot more in depth than I will.

# First Step: Hello, World!

In [ ]:
print("Hello, World!")

Hello, World!


# Basic math


In [ ]:
1 + 2 

3

Jupyter will only print the output of the last line in each cell.

In [ ]:
1 + 2
6 / 3

2.0

## 1

$$6 \times 5 - 6 \times 3^2 \times \frac{2^3}{4} \times 7 = -726.0$$

### answer

In [ ]:
6*5-6*3**2*2**3/4*7

-726.0

## 2
$$(6 \times 5 - (6 \times 3))^2 \times (\frac{(2^3)}{4} \times 7)$$


### answer

In [ ]:
(6*5-(6*3))**2*((2**3)/4*7)

2016.0

Much like order of operations, Python has rules for evaluating expressions. As we saw, for math, this means following pemdas.

In [ ]:
# First, evaluate what's inside the parentheses. Then, run `abs` on that value. 
abs(1.11 - 12.3)

11.190000000000001

# Variables and Types

In [ ]:
x = 10
x + 4

14

Variables are carried across cells.

In [ ]:
x + 2

12

Variable names in Python are traditionally lowercase, with underscores seperating the words. Variables should be descriptive and unique.

In [ ]:
starting_value = 2
difference = 4
ending_value = starting_value - difference
print(ending_value)

-2


You can update a variables value

In [ ]:
x = 3
print(x)

x = 4
print(x)

x = x + 1
print(x)

3
4
5


Variable names cannot collide with certain protected values in Python. These values will be distinguished with a different color.

In [ ]:
# INVALID
assert = 1
type = 1

SyntaxError: ignored

In [ ]:
biweekly_salary = 1240
monthly_salary = 2 * biweekly_salary
number_of_months_in_a_year = 12
yearly_salary = number_of_months_in_a_year * monthly_salary
yearly_salary

Each variable has a type associated with it. For example, numbers without a decimal are called integers, and numbers with a decimal are called floats. Other types include things like Strings, lists, or Pandas Dataframes.

To go from one type to another, or to enforce a type, you can _cast_ values from one type to another.

Python handles most type managment, but it can come up with errors occasionally.

In [ ]:
print(type(2.3))

print(type(1))
print(type(float(1)))

decimal = 2.3
whole_number = int(decimal)

print("Decimal types:")
print(decimal)
print(type(decimal))

print("Whole number types:")
print(whole_number)
print(type(whole_number))

<class 'float'>
<class 'int'>
<class 'float'>
Decimal types:
2.3
<class 'float'>
Whole number types:
2
<class 'int'>


In [ ]:
# You can also convert from a string to a float or integer. 
number_str = "1"
number_int = int(number_str)

print("String version: ", number_str, " string version type: ", type(number_str))
print("Int version: ", number_int, " Int version type: ", type(number_int))


String version:  1  string version type:  <class 'str'>
Int version:  1  Int version type:  <class 'int'>


A snippet of text is represented by a string value in Python. The word "string" is a computer science term for a sequence of characters. A string might contain a single character, a word, a sentence, or a whole book.

To distinguish text data from actual code, we demarcate strings by putting quotation marks around them. Single quotes (') and double quotes (") are both valid. The contents can be any sequence of characters, including numbers and symbols. 

In [ ]:
print("This is an example ", "of a string")

This is an example  of a string


There are some methods you can call on strings.

In [ ]:
# Replace one letter
'Hello'.replace('o', 'a')

'Hella'

In [ ]:
'hitchhiker'.replace('hi', 'ma')

'matchmaker'

# If statements and booleans

A boolean is true or false. This can also be represented as 1 (true) or 0 (false). At the lowest level, all computer programs are eventually reduced down to 1s and 0s. At a high level, booleans are very useful for branching logic. 

In [ ]:
true = True
false = False

if (true):
  print("This is true")

if (false):
  print("Since this is false, this line will not get printed")

if (not false):
  print("This is not false")

This is true
This is not false


In [ ]:
# Change me
a = True
b = False

if (a and b):
  print("Both a and b are true")

if (a or b):
  print("Either a or b is true (or both)")

if (a == b):
  print("A and b are equal")

if (a != b):
  print("a and b are not equal")

c = True

if (a == b and c):
  print("a and b are equal and c is true")

Either a or b is true (or both)
a and b are not equal


In [ ]:
is_a_bird = False
is_a_plane = False

if (not is_a_bird):
  print("Is it a bird? No")

if (not is_a_plane):
  print("Is it a plane? No")

if (not is_a_bird and not is_a_plane):
  print("It's superman!")


Is it a bird? No
Is it a plane? No
It's superman!


Booleans can also be created through equality statements with numbers (and lots of other ways.)

In [ ]:
x = 1
y = 3
c = True

if(x <= 10):
  print("x is less than or equal to 10")
if(x > -10 and x < 10):
  print("X is between -10 and 10")

  

x is less than or equal to 10
X is between -10 and 10


# Errors

## Syntax errors

A Syntax error is an error in the way the program is written. **Syntax** refers to the structure of a program and the rules about that structure. For example, in English, a sentence must begin with a capital letter and end with a period. this sentence contains a syntax error. So does this one

When these syntax errors are encountered in Python, the program will throw an error and stop.

In [ ]:
x = 3
if (x = 9:
    print("x is 9")

SyntaxError: ignored

## Logic Errors

Logic errors can be difficult to track down. The program may run without errors, but behave in unexpected or incorrect ways. 

In [ ]:
# This computes (2 + 4) / 3 = 2.
print(2 + 4 / 3)

3.333333333333333


In [ ]:
width = int(input("Please enter the width of a rectangle "))
height = int(input("Please enter the height of a rectangle "))

area = width * height
print("The area of the rectangle is " + str(area))

perimeter = width + width + height
print("The perimeter of the rectangle is " + str(area))


Please enter the width of a rectangle 1
Please enter the height of a rectangle 22
The area of the rectangle is 22
The perimeter of the rectangle is 22


## Runtime Errors

Finally, there are runtime errors, so called because the error does not appear until you run the program. These errors are also called exceptions because they usually indicate that something exceptional (and bad) has happened.

In [ ]:
width = int(input("Please enter the width of a rectangle "))
height = int(input("Please enter the height of a rectangle "))

area = width * height
print("The area of the rectangle is " + str(area))

perimeter = width + width + height
print("The perimeter of the rectangle is " + str(area))


Please enter the width of a rectangle st


ValueError: ignored

# Application: Manhattan Distance

Chunhua is on the corner of 7th Avenue and 42nd Street in Midtown Manhattan, and she wants to know far she'd have to walk to get to Gramercy School on the corner of 10th Avenue and 34th Street.

She can't cut across blocks diagonally, since there are buildings in the way.  She has to walk along the sidewalks.  Using the map below, she sees she'd have to walk 3 avenues (long blocks) and 8 streets (short blocks).  In terms of the given numbers, she computed 3 as the difference between 7 and 10, *in absolute value*, and 8 similarly.  

Chunhua also knows that blocks in Manhattan are all about 80m by 274m (avenues are farther apart than streets).  So in total, she'd have to walk $(80 \times |42 - 34| + 274 \times |7 - 10|)$ meters to get to the park.

<img src="https://github.com/cu-applied-math/stem-camp-notebooks/blob/master/2021/PythonIntro/figs/map.jpg?raw=1"/>

### QUESTION 1
Write some code to compute the distance Chunhua needs to walk. 

## Answer

In [ ]:
# Here's the number of streets away:
num_streets_away = abs(42-34)

# Compute the number of avenues away in a similar way:
num_avenues_away = abs(7-10)

street_length_m = 80
avenue_length_m = 274

# Now we compute the total distance Chunhua must walk.
manhattan_distance = street_length_m*num_streets_away + avenue_length_m*num_avenues_away

# We've included this line so that you see the distance
# you've computed when you run this cell.  You don't need
# to change it, but you can if you want.
manhattan_distance

1462

# Functions and methods

We have used some functions so far - things like `int()`, `print()`, and `input()` are all functions. What is a function? 

A function encapsulates a piece of code which can then be run easily without rewriting the code. All the functions we have used so far are built into Python. 

In [ ]:
# Using functions 
number = -10

# A function can take in a value
positive_number = abs(-10)

# or multiple values
bigger_number = max(number, positive_number)

print(f'Our starting number is {number}. The absolute value of that number is {positive_number}, and the maximum of those two numbers is {bigger_number}.')

Our starting number is -10. The absolute value of that number is 10, and the maximum of those two numbers is 10.


##### Multiple arguments
Some functions take multiple arguments, separated by commas. For example, the built-in `max` function returns the maximum argument passed to it.

In [ ]:
max(2, -3, 4, -5)

4

You can define your own functions. Although functions can return values, they don't have to. This is an example of a function that does not return a value. 

In [ ]:
# Our own max function
def custom_max(first, second):
  if (first >= second):
    print("The first is bigger than the second")
  else:
    print("The second is bigger than the first")



In [ ]:
custom_max(10, 11)

test_variable = custom_max(10, 11)
print(test_variable)

The second is bigger than the first
The second is bigger than the first
None


To return something, we use the return key word. The best practice is to only return one thing at the end of the function.

In [ ]:
def returnable_max(first, second):
  max = None
  if (first >= second):
    max = first
  else:
    max = second
  return max

In [ ]:
returnable_max(10, 11)

test_variable = returnable_max(10, 11)
print(test_variable)

11


In [ ]:
# A function doesn't need to return anything, or accept any variables.
def say_hi():
  print("Hi!")

In [ ]:
say_hi()

Hi!


The variables inside a function are unique to the inside of this function. This means you can have clashing variable names without having them interact.

In [ ]:
def add_up(x, y):
  z = 10
  return x + y + z

x = 1
y = 1
z = 3
add_up(x, y)

12

You can also call what is called a *method* from a class. You can think of a class like a type, similar to what we talked about earlier. Each class has a specific set of rules and methods which can be applied to *members* of that class.

A string is one example of this. We've already seen string methods:

In [ ]:
sharp = 'edged'
# Replace is a _method_ that is applied to sharp. 
hot = sharp.replace('ed', 'ma')
print('sharp =', sharp)
print('hot =', hot)

In [ ]:
# These methods can be applied on any string, and returns a string itself.
fixed_typo = "hello gorld!".replace('g', 'w')
print(fixed_typo)
print(type(fixed_typo))

# you can chain them together
'train'.replace('t', 'ing').replace('in', 'de')

Another example of a class is the `math` class. Here are some math methods:

In [ ]:
import math

# Return the factorial of the input
print(math.factorial(3))

# return the largest integer less than or equal to x
print(math.floor(2.9))

# With one argument, return the natural logarithm of the input.
print(math.log(12))

# with two inputs, return the logarithm of the first input to the given base (log(x)/log(base))
print(math.log(23, 2))

6
2
2.4849066497880004
4.523561956057013


### What kinds of errors can you get with functions?

## Possible errors

In [ ]:
# wrong number of arguments
print(returnable_max(1))

TypeError: ignored

In [ ]:
# Expecting a return from a function without a return statement
max_value = custom_max(12, 13)
print(max_value + 1)

The second is bigger than the first


TypeError: ignored

In [ ]:
# Mismatching types
custom_max(1, "hi!")

TypeError: ignored

## Exercise:
Take your code that calculates the manhattan distance, above, and put it into a function. This function should take in the starting street, the ending street, the starting avenue, and the ending avenue, and return the distance walked. Remember that an avenue is 274m, and a street is 80m

**Example input**: `compute_manhattan_dist(42, 34, 7, 10)`

**Expected output**: 1462

In [ ]:
def compute_manhattan_dist(start_st, end_st, start_ave, end_ave):
  return 0

# Lists

A list is an ordered set of values, where each value is identified by an index. The values that make up a list are called its elements. Lists are similar to strings, which are ordered sets of characters, except that the elements of a list can have any type.

In [ ]:
[1, 2, 3, 4]
["a", "b", "c"]
[1, "cat", [2, 3]]

To access values inside a list, we can use brackets

In [ ]:
list_1 = [1, 10, 20]
print(list_1[1])

10


You can even go backwards:

In [ ]:
print(list_1[-1])

20


You can update a value in a list the same way

In [ ]:
list_1[0] = 100
print(list_1)

[100, 10, 20]


In [ ]:
list_1.append(1)
print(list_1)

[100, 10, 20, 1, 1]


You can access a subsection of a list through a **slice**

In [ ]:
list_2 = list_1[0:2]

print(list_2)

print(list_1[1:])

[100, 10]
[10, 20]


You can have n dimensional lists

In [ ]:
matrix = [[1, 2, 3],[5, 6, 7]]
print(matrix[0])
print(matrix[1][2])

[1, 2, 3]
7


In [ ]:
print(len(matrix))
print(len(matrix[0]))

2
3


In [ ]:
empty_list = []

if not empty_list:
  print("This list is empty")

This list is empty


### What kind of errors can you get with lists?

## Possible errors

In [ ]:
list_1[3]

IndexError: ignored

In [ ]:
list_1[-4]

IndexError: ignored

In [ ]:
list_1[6] = 2


IndexError: ignored

# Loops

Repeated execution of a set of statements is called iteration. Because iteration is so common, Python provides several language features to make it easier. The first feature we are going to look at is the while statement.

In [ ]:
x = 0
while x < 5:
  print(x)
  x = x + 1

0
1
2
3
4


In [ ]:
for item in [1, 2, 3, 4]:
  print(item)

1
2
3
4


# Exercise: Lists

Given a list, output another list with each value squared.

numbers = [1, 2, 3, 4, 5, 6, 7]

Expected output:
[1, 4, 9, 16, 25, 36, 49]

In [ ]:
numbers = [1, 2, 3, 4, 5, 6, 7]

## Final Exercise 
Write a function which accepts a list of starting and ending streets, and a list of starting and ending avenues. For each set of start and end points, call your manhattan distance function from before and return a list of the distance walked for each set of starting and ending points.

**Example input**: 
streets = `[[1, 22], [4, 11], [23, 29]]`

avenues = `[[2, 9], [33, 2], [30, 41]]`

So the first set of points, you would be walking from 1st street, 2nd avenue, to 22nd street, 9th avenue. 

**Expected output:**:


In [ ]:
def compute_multiple_distances(streets, avenues):
  return []

### Answer

In [ ]:
def compute_multiple_distances(streets, avenues):
  index = 0
  results = []
  while index < len(streets):
    street_pair = streets[index]
    ave_pair = avenues[index]
    print(street_pair)
    dist = compute_manhattan_dist(street_pair[0], street_pair[1], ave_pair[0], ave_pair[1])
    results.append(dist)
    index = index + 1
  return results

compute_multiple_distances([[1, 2]], [[1,1]])

[1, 2]


[0]

# Application: Applying numpy and pandas

Numpy and pandas are two python packages commonly used for data science applications. Numpy is a package which greatly improves on the existing math and data storage capablities of Python. Pandas is a package for creating and manipulating excel-like tables for managing data. 

In [ ]:
import numpy as np 

np.array([0.125, 4.75, -1.3])

array([ 0.125,  4.75 , -1.3  ])

In [ ]:
np.shape(np.array([[1.1, 2.2], [22, 0.11]]))

(2, 2)

**Arrays Vs Lists**
Arrays are a lot more efficient than lists. In addition, you can apply many useful numpy functions to the numpy arrays. In general, if it's something simple, a list is fine, but if you're manipulating real data, then a numpy array is worth using. However, it is very inefficient to add onto the end of an array - it's preferable to create the array at the size you want. 

In [ ]:
numpy_array = np.zeros((2, 4, 3))
print(np.shape(numpy_array))
print(numpy_array)

(2, 4, 3)
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
numpy_array[0][2][0] = 4
print(numpy_array)


[[[0.  0.  0. ]
  [0.  0.  0. ]
  [4.  0.  0. ]
  [0.  0.  0. ]]

 [[0.  0.  0. ]
  [0.  0.  0. ]
  [0.  0.  0. ]
  [2.2 2.3 2.4]]]


In [ ]:
numpy_array[1][3] = np.array([2.2, 2.3, 2.4])
print(numpy_array)

[[[0.  0.  0. ]
  [0.  0.  0. ]
  [4.  0.  0. ]
  [0.  0.  0. ]]

 [[0.  0.  0. ]
  [0.  0.  0. ]
  [0.  0.  0. ]
  [2.2 2.3 2.4]]]


Exercise:
Make an array containing the numbers 0, 1, -1, $\pi$, and $e$, in that order.  Name it `interesting_numbers`.  

np.arange(start, stop, space) produces an array with all the numbers starting at start and counting up by space, stopping before stop is reached.

In [ ]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

Exercise:

NOAA (the US National Oceanic and Atmospheric Administration) operates weather stations that measure surface temperatures at different sites around the United States. The hourly readings are publicly available.

Suppose we download all the hourly data from the Oakland, California site for the month of December 2015. To analyze the data, we want to know when each reading was taken, but we find that the data don't include the timestamps of the readings (the time at which each one was taken).

However, we know the first reading was taken at the first instant of December 2015 (midnight on December 1st) and each subsequent reading was taken exactly 1 hour after the last.

Create an array of the time, in seconds, since the start of the month at which each hourly reading was taken. Name it collection_times.

Hint: There were 31 days in December, which is equivalent to 31×24
hours or 31×24×60×60 seconds. So your array should have 31×24

elements in it.

Hint 2: The len function works on arrays, too. If your collection_times isn't passing the tests, check its length and make sure it has 31×24
elements.

### Pandas

Similar to Numpy arrays, pandas has a data structure as well.

The equivalent to an array in pandas is called a **series**. A series is basically a one dimensional array.

It also has a more complex data structure, called a **dataframe**. This is like a 2-dimensional array. It's easiest to think of this as like an excel spreadsheet. 

In [ ]:
import pandas as pd 

first_series = pd.Series([1, 2, 3, 4])
print(first_series)

second_series = pd.Series(np.array([2, 3, 4, 5]))
print(second_series)

0    1
1    2
2    3
3    4
dtype: int64
0    2
1    3
2    4
3    5
dtype: int64


In [ ]:
dates = pd.date_range("20130101", periods=6)

print("dates: ", dates)

dates:  DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')


In [ ]:
# Create a dataframe with an index of the given dates, and the columns A-D. This is filled with a randomly generated array of size (6, 4)
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

A         B         C         D
2013-01-01 -0.082632 -0.183514 -1.452341  0.258643
2013-01-02 -1.032206  0.914198 -1.749963  1.536343
2013-01-03  0.335698  0.718498  0.252951  0.263295
2013-01-04  1.365506 -0.503895 -0.386536  1.239624
2013-01-05  0.277528  1.068822 -0.606834 -0.793014
2013-01-06 -0.856231 -1.283453 -0.769701 -1.208735

# Sources

https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html

http://openbookproject.net/thinkcs/python/english2e/index.html

